version: 0.2

phases:
  pre_build:
    commands:
      - # Your other pre_build commands here
      

  build:
    commands:
      - # Your other build commands here
      - echo "Installating  packages..."
      - yum update -y
      - yum upgrade -y
      - yum install amazon-linux-extras -y
      - amazon-linux-extras | grep php
      - amazon-linux-extras enable php7.4
      - amazon-linux-extras install php7.4
      - yum clean metadata
      - yum install php-cli php-pdo php-fpm php-json php-mysqlnd -y
      - yum install git -y
      - sudo yum install ruby -y
      - sudo yum install wget -y
      - rm -rf /var/www/html/*
      - rm -rf /var/www/html/.htaccess 
      - sudo yum install php-mbstring php-xml -y
      - sudo su
      - cd /var/www/html
      - wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      - mkdir phpMyAdmin && tar -xvzf phpMyAdmin-latest-all-languages.tar.gz -C phpMyAdmin --strip-components 1
      - rm phpMyAdmin-latest-all-languages.tar.gz
      - sudo systemctl start mariadb
      - cd phpMyAdmin 
      - sudo mv config.sample.inc.php config.inc.php
      - sudo vi config.inc.php

      
  post_build:
    commands:
      - # Your other post_build commands here
      - sudo su
      - cd ~
      - wget https://aws-codedeploy-af-south-1.s3.af-south-1.amazonaws.com/latest/install
      - chmod +x ./install
      - sudo ./install auto
      
      
artifacts:
  files:
    - '**/*'
    - '!application/config/database.php.ci'
    - '!application/config/config.php.ci'